export const CREATE_ITEM = "CREATE_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const GET_ITEMS = "GET_ITEMS";
export const GET_ALL_ITEMS = "GET_ALL_ITEMS";
export const SELECTED_ITEM_LISTENER = "SELECTED_ITEM_LISTENER";
export const SELECTED_ITEM_CLEAR = "SELECTED_ITEM_CLEAR";
export const CLEAR_ITEMS = "CLEAR_ITEMS";
export const RETAIN_STATE = "RETAIN_STATE";
export const RETAIN_STATE_CLEAR = "RETAIN_STATE_CLEAR";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const UPDATE_IMAGE = "UPDATE_IMAGE";

export const SET_CATEGORY = "SET_CATEGORY";

export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const SET_LOADER = "SET_LOADER";
export const CLEAR_LOADER = "CLEAR_LOADER";

export const APP_INIT = "APP_INIT";

export const CURRENT_USER_PROFILE_GET = "CURRENT_USER_PROFILE_GET";
export const SELECTED_USER_PROFILE = "SELECTED_USER_PROFILE";

export const COMMENT_LISTENER = "COMMENT_LISTENER";

export const FOLLOWERS_LISTENER = "FOLLOWERS_LISTENER";
export const FOLLOWINGS_LISTENER = "FOLLOWINGS_LISTENER";

export const USER_IS_FOLLOWING = "USER_IS_FOLLOWING";
export const USER_IS_NOT_FOLLOWING = "USER_IS_NOT_FOLLOWING";
export const CLEAR_FOLLOWINGS_ON_LEAVE = "CLEAR_FOLLOWINGS_ON_LEAVE";
